name: "Client CI"

on:
  pull_request:
    branches:
      - "main"
  workflow_call:

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the client app"
        run: "yarn build"
