name: "Deploy and Pin"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    uses: "./.github/workflows/tests.yml"
  deploy:
    needs: "test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Preflight: checkout"
        uses: "actions/checkout@v4"

      - name: "Deps: install bun"
        uses: "oven-sh/setup-bun@v1"

      - name: "Deps: install node modules"
        run: "bun install --frozen-lockfile"

      - name: "Run: build project"
        run: "bun run build"

      - name: "IPFS: upload bundle and pin"
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@a551f37c17ec3961df7c3ad52e1cd266dfd3d7e7
        with:
          pin-name: Uniswap Default Token List
          path: "build/sablier-community.tokenlist.json"
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: "IPFS: hash summary"
        run: |
          echo "Successfully deployed on IPFS: [${{ steps.upload.outputs.hash }}](https://cloudflare-ipfs.com/ipfs/${{
            steps.upload.outputs.hash }})"

      - name: "Cloudflare: update DNS with latest IPFS hash"
        env:
          CLOUDFLARE_GATEWAY_ID: ${{ secrets.CLOUDFLARE_GATEWAY_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: "sablier-labs/action-cloudflare-web3-gateway@main"
        with:
          cid: ${{ steps.upload.outputs.hash }}
