name: "Tokenlist IPFS Deployment"

on: [push]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the client app"
        run: "yarn build"

      - name: Pin to IPFS
        id: upload
        uses: aquiladev/ipfs-action@master
        with:
          path: 'build/sablier-default.tokenlist.json'
          service: 'infura'
          pinName: 'tokenlist'
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: Create commit comment with IPFS hash
        uses: peter-evans/commit-comment@v2
        with:
          body: 'Successfully deployed on IPFS: [${{ steps.upload.outputs.hash }}](https://cloudflare-ipfs.com/ipfs/${{ steps.upload.outputs.hash }})'
