name: "Tests"

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install Node.js dependecies"
        run: "yarn install --frozen-lockfile"

      - name: "Test: run test suite"
        run: "yarn test"
