name: "Tests"

on: 
  push:
  pull_request:
    
jobs:
  test:
    runs-on: "ubuntu-latest"

    name: "Unit Tests"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - run: "yarn install --frozen-lockfile"

      - run: "yarn test"
