name: "Tests"

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Preflight: checkout the repo"
        uses: "actions/checkout@v4"

      - name: "Deps: install bun"
        uses: "oven-sh/setup-bun@v1"

      - name: "Deps: install node modules"
        run: "bun install --frozen-lockfile"

      - name: "Run: test suite"
        run: "bun run test"
